### ISSUE TITLE
Naming conventions are not idiomatic

### ISSUE THREAD

**Issue by alok87** [bvwells/go-patterns#38]
Some naming conventions follow the java kind of naming convention like .
a.GetResult() instead of a.Result()

A good video on naming convention in go: https://www.youtube.com/watch?v=MzTcsI6tn-0&t=78s

"Write go like go team"

**Comment by bvwells** [comment]
Many thanks for the issue. I believe that your main issue lies with getters having 'Get' in the method name. From my knowledge the original guidance on this comes from Effective Go (https://go.dev/doc/effective_go#Getters).

From what I can see there are two instances of this:

https://github.com/bvwells/go-patterns/blob/cda58ba4b1cf47eab0eae13a9fd37617b4bd7880/creational/builder.go#L48
https://github.com/bvwells/go-patterns/blob/cda58ba4b1cf47eab0eae13a9fd37617b4bd7880/structural/flyweight.go#L26

In terms of idiomatic Go code I tend to agree with Dave Cheney:
```
My concern with the mantra of idiomatic Go is, in many ways, it can be exclusionary. It’s saying “you can’t sit with us.” After all, isn’t that what we mean when critique of someone’s work as non-idiomatic? They didn’t do It right. It doesn’t look right. It doesn’t follow the style of time.

I offer that idiomatic Go is not a suitable mechanism for teaching how to write good Go code because it is defined, fundamentally, by telling someone they did it wrong. Wouldn’t it be better if the advice we gave didn’t alienate the author right at the point they were most willing to accept it?
```
https://dave.cheney.net/2020/02/23/the-zen-of-go

The main aim of these examples is to show how the patterns documented by the Gang of Four could be implemented in Go. If you feel that changing the names of these setters adds something to the clarity of the examples then please feel free to raise a pull request.

**Comment by alok87** [comment]
Thanks for sharing the Dave Cheney's article. Read it. Agree.
