### ISSUE TITLE
Go - Concurrency Design Patterns

### ISSUE THREAD

**Issue by mrasyidg** [bvwells/go-patterns#42]
I think it'd be great if someone could add a concurrency design patterns section/part (goroutine & channels, select, fan-In & fan-out, mutex, etc.)!

**Comment by bvwells** [comment]
@mrasyidg many thanks for submitting an issue. Unfortunately I missed it.

I've tried to keep the patterns described here to be the ones described in [Design Patterns: Elements of Reusable Object-Oriented Software (1994)](https://en.wikipedia.org/wiki/Design_Patterns) by the Gang of Four. In that sense I see the examples as kind of complete.

**Comment by mrasyidg** [comment]
Hi, @bvwells! 

Don't mind about the issue that I made. I realized what you said and thus closed this issue.

I think I have been looking for a different set of patterns. I should have looked for Go's sets of best practices and patterns specific to its paradigm.

Although, this also gets me a bit more curious, GoF's book lists OOP design patterns (like the ones in the repo), which may not be applicable to or even go against Go's features and philosophy (creators initial intention etc.). For example, the Singleton pattern, may not be a good fit for Go's focus on concurrency and minimizing shared state.

My question is, how is your view on this?

Thank you! 🙏

---

PS. Please don't take my question as a critic because it's not. That is a genuine question. If I could recall from the earlier years after this language was released, some devs wanted to implement OOP with this language. I also was asked to learn how to implement OOP with Go by my employer. That was actually the main reason I searched this topic; to brush up some practices after I recall something 😅. I also have found some generic OOP patterns implemented on some Go projects.
